version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: tms-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=qwerty
        - MYSQL_DATABASE=shoplist
        - MYSQL_USER=shoplist
        - MYSQL_PASSWORD=qwerty
      ports:
        - "1027:3306"
      networks:
        - isolated
        
    frontend:
      stdin_open: true
      container_name: tms-ui
      build:
          context: .
          dockerfile: docker/ui/Dockerfile
      volumes:
          - './ui:/app'
          - '/app/node_modules'
      ports:
          - 1025:3000
      environment:
          - CHOKIDAR_USEPOLLING=true
      networks:
          - isolated
       
    backend-nginx:
      image: nginx:alpine
      container_name: tms-api-web
      working_dir: /application
      volumes:
          - ./api:/application
          - ./docker/backend-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1024:80"
      networks:
       - isolated
      
    php-fpm:
      build: docker/php-fpm
      container_name: tms-api-php
      working_dir: /application
      volumes:
        - ./api:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        - ./docker/php-fpm/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      networks:
        - isolated
      environment:
        XDEBUG_CONFIG: "remote_host=${localIp}"
networks:
  isolated:
    external:
      name: prototype_net

